### ISSUE TITLE
[AP] Style Suite

### ISSUE THREAD

**Issue by FortreeForums** [FortreeForums/FortreeForums#12]
Once I've finished migrating our custom fields into addons, I'll combine those addons into one mega-suite

**Avatar frames**
- [x] Patch into account details
- [x] Avatar Frames
- [x] Avatar Frames preview
    - [x] Preview doesn't work if added via template modification, it must be hardcoded in. Maybe because its a jQuery?

**Usernames**
- [x] Create page
- [x] Create permissions
- [x] Create phrases
- [x] Delete entity (see #18)
- [x] Sparkle
- [x] Color
- [x] Glow
    - [x] Glow strengths
- [x] Bold 
- [x] Italic
- [x] Underline
- [x] Font
- [x] Username Preview

**Custom title**
- [x] Create page
- [x] Create permissions
- [x] Create phrases
- [x] Delete entity (see #18)
- [x] Sparkle
- [x] Color
- [x] Glow
    - [x] Glow strengths
- [x] Bold
- [x] Italic
- [x] Underline
- [x] Font
- [x] Custom title preview

**Postbit**
- [x] Create page
- [x] Create permissions
- [x] Create phrases
- [x] Delete entity (see #18)
- [x] Disable
- [x] BG
- [x] Color
- [x] Shadow
- [x] CSS      
- [x] Postbit Preview

**Profile**
- [x] Create page
- [x] Create permissions
- [x] Create phrases
- [x] Create entity
- [x] Header
- [x] Navbar BG
- [x] Page Background
- [x] Font color
- [x] URL color
- [x] Highlight color
- [x] Box header
- [x] Box BG
- [x] Border color
- [x] Border alt color
- [x] CSS
- [x] Profile Preview

**Suite Exclusive**
- [x] Admin Page
    - [x] Allow configuring of border with (standard & index)
    - [x] Allow global disabling of each section
        - [x] Frame
        - [x] Username
        - [x] Title
        - [x] Postbit
        - [x] Profile
    - [x] Allow admins to change a users settings
        - [x] Frame
        - [x] Username
        - [x] Title
        - [x] Postbit
        - [x] Profile
        - [x] Replace regular permissions in admin page with admin permissions
- [x] Combine all permissions into new category

**Final Cleanups for Public Release**
- [x] Create "public" folder
- [x] Remove apathy/chaos/nyko avatar frames
- [x] Remove link to Profile template in phrases
- [x] Replace sparkle names in templates with phrases
- [x] Actually add font options
- [x] Remove ap_rep_bars and ap_activity_longevity from postbit preview
- [x] Custom title settings on User Editing has broken phrases
- [x] Custom title sparkle spans full postbit in conversations and whole row on Current Visitors
- [x] Apply Postbits to conversations
- [x] Profile Border field doesnt work on ChatBanter
- [x] Replace frame names with phrases in templates
- [x] Profile highlight color phrase broken
- [x] Verify colors/url inputs
    - [x] Frames 
    - [x] Profiles
- [x] Avatar frame doesnt save on Chatbanter
- [x] Force avatars to be square if avatar frames are enabled
- [x] Glow previews only format the color, not the strength (text-shadow: #ffffff;)
- [x] Custom glow strength's dont affect the preview
- [x] Add explanations to the postbit settings
- [x] Fix #20
- [x] Rebase profile header css off stock xenforo skin
- [x] Regular Profile Styles permission group is collapsed by default
- [x] Broken [AP] Avatar Frames permission group name phrase
- [x] Replace hardcoded Profile preview text with phrases
- [x] GET WORKING FONTS FOR UN/TITLE

**Comment by FortreeForums** [comment]
We could try allow for username customization such as shown here -> https://tappedout.net/users/Femme_Fatale/
Apparently the users of this site can customize by the letter, so I can't imagine it would be very easy....

**Comment by FortreeForums** [comment]
This add-on should be complete as of 7d28916.

Per-letter control, addressed in the previous comment, and animated glows, should be investigated in the future.
Everything in the to-do list has been addressed and implemented. For now, we just fix bugs until the official Xenforo release.
